config/routes.rb
Rails.application.routes.draw do
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  resource :cart, only: [:show, :destroy] do
    post 'add_item/:product_id', to: 'carts#add_item', as: 'add_item'
    post 'add_item_cart/:product_id', to: 'carts#add_item_cart', as: 'add_item_cart'
    delete 'remove_item/:product_id', to: 'carts#remove_item', as: 'remove_item'
    delete 'empty_cart', to: 'carts#empty_cart', as: 'empty'
    patch 'decrease_quantity'
  end
  
  # Catch-all route for handling non-existent routes
  match "*path", to: "application#render_404", via: :all, constraints: lambda { |req| !req.path.start_with?('/assets') && !req.path.start_with?('/rails') }

  # Defines the root path route ("/")
  root "products#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Shop" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Bootstrap CSS CDN %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    <%# Font Awesome CDN %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      body {
        background-image: url('<%= asset_path("bg-flatphone.jpg") %>');
        background-size: cover;
        background-position: center center;
        background-attachment: fixed;
        padding-top: 140px; 
        padding-bottom: 70px;
      } 
      header {
        background-size: cover;
        background-position: center center;
        background-attachment: fixed;
      }
    </style>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg fixed-top navbar-light mb-4 py-4">
        <div class="container bg-warning">
          <%= link_to "MyShop", root_path, class: "navbar-brand ms-5" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto align-items-center">
              <li class="nav-item dropdown">
                <% if user_signed_in? %>
                  <!-- Logged in user -->
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Welcome, <%= current_user.name %>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                      <i class="fa fa-user-circle me-2"></i>Edit Profile
                    <% end %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= button_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                      <i class="fa fa-sign-out-alt me-2"></i>Sign Out
                    <% end %></li>
                  </ul>
                <% else %>
                  <!-- Not logged in -->
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Account
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><%= link_to new_user_session_path, class: "dropdown-item" do %>
                      <i class="fa fa-sign-in-alt me-2"></i>Sign In
                    <% end %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to new_user_registration_path, class: "dropdown-item" do %>
                      <i class="fa fa-user-plus me-2"></i>Sign Up
                    <% end %></li>
                  </ul>
                <% end %>
              </li>

              <!-- Cart -->
              <li class="nav-item ms-2">
                <% if user_signed_in? %>
                  <%= link_to cart_path(@cart), class: 'nav-link position-relative' do %>
                    <i class="bi bi-cart fs-2"></i> Cart  
                    <span class="position-absolute top-0 start-50 translate-middle-x badge rounded-pill bg-danger">
                      <%= @cart.line_items.sum(:quantity) %>
                    </span>
                  <% end %>
                <% else %>
                    <%= link_to new_user_session_path, class: 'nav-link position-relative' do %>
                    <i class="bi bi-cart fs-2"></i> Cart  
                    <span class="position-absolute top-0 start-50 translate-middle-x badge rounded-pill bg-danger">
                      <%= @cart.line_items.sum(:quantity) %>
                    </span>
                  <% end %>
                <% end %>
              </li>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="flash-messages position-fixed top-0 start-50 translate-middle-x p-5 w-50" style="z-index: 1050;">
      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show alert-fade" role="alert">
          <i class="fas fa-check-circle me-2"></i>
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      <% end %>
      
      <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show alert-fade" role="alert">
          <%= alert %>
          <i class="fas fa-check-circle me-2"></i>
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      <% end %>
    </div>

    <main>
      <%= yield %>
    </main>

    <footer class="footer py-0 bg-warning fixed-bottom">
      <div class="container text-center">
        <p class="text-muted">&copy; <%= Time.current.year %> MyShop. All rights reserved.</p>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>